FROM manjarolinux/base

# install dependencies
RUN pacman -Sy --noconfirm yay ffmpeg img2pdf sox youtube-dl imagemagick tesseract tesseract-data-chi_tra python-pip neovim openssh redis

# install necessary Python pacakges
RUN pip install \
    webrtcvad \
    imagehash \
    python-pptx \
    pytesseract \
    opencv-python \
    rq \
    flask \
    requests

# clone video-summarizer
RUN mkdir development
RUN git clone https://github.com/video-summarizer-platform/Video-Summary.git
RUN mv Video-Summary development
RUN
